language: ruby
rvm:
  - 2.1.6
  - 2.2.2
gemfile:
  - gemfiles/rails_3.gemfile
  - gemfiles/rails_41.gemfile
  - gemfiles/rails_42.gemfile
addons:
  postgresql: "9.3"
before_script:
  - cp test/internal/config/database.yml.travis test/internal/config/database.yml