# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "activerecord-postgres-composite-types"
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Rafal Bigaj"]
  s.date = "2014-09-09"
  s.description = "This gem adds support to the ActiveRecord (3.x and 4.x) for composite types."
  s.email = "rafal.bigaj@puzzleflow.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".travis.yml",
    "Gemfile",
    "LICENSE",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "activerecord-postgres-composite-types.gemspec",
    "activerecord-postgres-custom-types.gemspec",
    "lib/activerecord-postgres-composite-types.rb",
    "lib/activerecord-postgres-composite-types/active_record.rb",
    "lib/activerecord-postgres-composite-types/active_record_3.rb",
    "lib/activerecord-postgres-composite-types/active_record_4.rb",
    "lib/activerecord-postgres-composite-types/composite_type_parser.rb",
    "lib/activerecord-postgres-composite-types/postgres_composite_type.rb",
    "lib/activerecord-postgres-composite-types/railties.rb",
    "test/composite_types.rb",
    "test/helper.rb",
    "test/internal/config/database.yml",
    "test/internal/config/database.yml.travis",
    "test/internal/db/schema.rb",
    "test/test_composite_type_class.rb",
    "test/test_nested_types.rb",
    "test/test_postgres_composite_types.rb"
  ]
  s.homepage = "http://github.com/puzzleflow/activerecord-postgres-composite-types"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "2.0.3"
  s.summary = "ActiveRecord composite types support"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activerecord>, [">= 3.2.0"])
      s.add_runtime_dependency(%q<pg>, [">= 0.17.0"])
      s.add_development_dependency(%q<test-unit>, ["~> 2.1"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<rake>, ["~> 10.3"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_development_dependency(%q<combustion>, ["~> 0.5.2"])
    else
      s.add_dependency(%q<activerecord>, [">= 3.2.0"])
      s.add_dependency(%q<pg>, [">= 0.17.0"])
      s.add_dependency(%q<test-unit>, ["~> 2.1"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<rake>, ["~> 10.3"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<combustion>, ["~> 0.5.2"])
    end
  else
    s.add_dependency(%q<activerecord>, [">= 3.2.0"])
    s.add_dependency(%q<pg>, [">= 0.17.0"])
    s.add_dependency(%q<test-unit>, ["~> 2.1"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<rake>, ["~> 10.3"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<combustion>, ["~> 0.5.2"])
  end
end

